apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: webui-cpu-util
spec:
  query: (sum:kubernetes.cpu.usage.total{kube_container_name:teastore-webui}/sum:kubernetes.cpu.limits{kube_container_name:teastore-webui})/10000000
