apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: auth
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-auth
  metrics:
  - type: External
    external:
      metricName: datadogmetric@default:auth-cpu
      targetAverageValue: 80
