apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: persistence
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-persistence
  metrics:
  - type: External
    external:
      metricName: datadogmetric@default:persistence-cpu
      targetAverageValue: 80
