apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: webui
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-webui
  metrics:
  - type: External
    external:
      metricName: datadogmetric@default:webui-cpu
      targetValue: 80
